version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing PostgreSQL client"
      - sudo apt update -y
      - sudo apt install -y postgresql
      # - sudo apt install dnsutils
      
  pre_build:
    commands:
      - echo "Preparing environment"
      - export PGPASSWORD="$DB_PASSWORD"
      - pwd
      # Verify libpq installation
      - psql --version
      # - rpm -qa | grep libpq
      # - dpkg -l | grep libpq
      # - ls -la
      # - psql -h "<rds>.amazonaws.com" -U "postgres" -d "sd_firstdb" -c "SELECT 1;"
  build:
    commands:
   
     # Set Database connection parameters
      
     - |
      
       DB_HOST="selva-geneartdb.c7gozccxmuzm.us-east-1.rds.amazonaws.com"
       DB_PORT="5432"
       DB_NAME="geneart"
       DB_USER="postgres"
       DB_PASSWORD="$DB_PASSWORD"
       export PGPASSWORD="$DB_PASSWORD"
       echo "Running database script"
     # DB_PASSWORD="postgres"
     # SQL_FILE="./release1.sql"
     # - . ./sd-script1.sh
     # Connect to the database
     - psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;"