version: 0.2

env:
  variables:
    DB_HOST: "selva-geneartdb.c7gozccxmuzm.us-east-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "geneart"
    DB_USER: "postgres"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing PostgreSQL client"
      - sudo apt update -y
      - sudo apt install -y postgresql
      # - sudo apt install dnsutils
      
  pre_build:
    commands:
      - echo "Preparing environment"
      # - export PGPASSWORD="$DB_PASSWORD"
      - pwd
      # - echo "db password" $PGPASSWORD
      # Verify libpq installation
      - psql --version
      - mkdir -p /tmp  # Create the /tmp directory
      - touch /tmp/sd-script1.log  # Create the log file
      # - rpm -qa | grep libpq
      # - dpkg -l | grep libpq
      # - ls -la
      # - psql -h "<rds>.amazonaws.com" -U "postgres" -d "sd_firstdb" -c "SELECT 1;"
  build:
    commands:
      # Set Database connection parameters
      - echo "Running database script"
      - chmod +x ./script/sd-script1.sh
      # - psql -q -h "selva-geneartdb.c7gozccxmuzm.us-east-1.rds.amazonaws.com" -p "5432" -U "postgres" -d "geneart"  -f "release1.sql"
      - bash ./script/sd-script1.sh
  post_build:
    commands:
      - echo "Displaying log file"
      - cat /tmp/sd-script1.log

artifacts:
  files:
    - /tmp/sd-script1.log