version: 0.2

env:
      variables:
        DB_HOST: "selva-geneartdb.c7gozccxmuzm.us-east-1.rds.amazonaws.com"
        DB_PORT: "5432"
        DB_NAME: "geneart"
        DB_USER: "postgres"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing PostgreSQL client"
      - sudo apt update -y
      - sudo apt install -y postgresql
      # - sudo apt install dnsutils
      
  pre_build:
    commands:
      - echo "Preparing environment"
      - export PGPASSWORD=$DB_PASSWORD  # Set PGPASSWORD for psql to use
      - echo "Testing connectivity to the database host..."
      - echo "Checking if database is ready..."
      - pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER"
      
  build:
    commands:
      - echo "Running database script"
      - ../sd-script1.sh

artifacts:
  files:
    - sd-script1.sh
    - release1.sql