version: 0.2

env:
  variables:
    variables:
    AWS_ROLE_ARN: "arn:aws:iam::073139075499:policy/sd-codecommit"
    AWS_ROLE_SESSION_NAME: "CodeBuildSession"
    EXPORT_FILE: "db_export.sql"

phases:
  install:

    runtime-versions:
      python: 3.x
    commands:
      - echo Logging in to Amazon RDS...
      - sudo apt update -y
      - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - sudo apt-get update
      - sudo apt install -y postgresql-client-14
      - sudo apt-get install -y awscli git
      - aws secretsmanager get-secret-value --secret-id sd-DatabaseCredentials --query 'SecretString' --output text > /tmp/secrets.json
      - export DB_HOST=$(jq -r '.DB_HOST' /tmp/secrets.json)
      - export DB_PORT=$(jq -r '.DB_PORT' /tmp/secrets.json)
      - export DB_NAME=$(jq -r '.DB_NAME' /tmp/secrets.json)
      - export DB_USER=$(jq -r '.DB_USER' /tmp/secrets.json)
      - export DB_PASSWORD=$(jq -r '.DB_PASSWORD' /tmp/secrets.json)
      - export NEW_DB_HOST=$(jq -r '.NEW_DB_HOST' /tmp/secrets.json)
      - export NEW_DB_PORT=$(jq -r '.NEW_DB_PORT' /tmp/secrets.json)
      - export NEW_DB_NAME=$(jq -r '.NEW_DB_NAME' /tmp/secrets.json)
      - export NEW_DB_USER=$(jq -r '.NEW_DB_USER' /tmp/secrets.json)
      - export NEW_DB_PASSWORD=$(jq -r '.NEW_DB_PASSWORD' /tmp/secrets.json)
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      

  pre_build:
    commands:
      - echo "Starting DB export..."

  build:
    commands:
      - export PGPASSWORD=$NEW_DB_PASSWORD
      - echo Executing the SQL script...
      - chmod +x ./script/backupsql.sh
      - bash ./script/backupsql.sh
      - echo "Exported data from new DB instance."
      - git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sd_imgdb
      - cd sd_imgdb
      - ls -l
      - echo "Moving export file to sd_imgdb/datafile/"
      - mv $EXPORT_FILE datafile/
      - echo "Listing sd_imgdb/datafile/ directory contents after moving file:"
      - ls -l sd_imgdb/datafile/
      - git config --global user.email "selvadhurai.gunasekaran@sanfordhealth.org"
      - git config --global user.name "selva"
      - echo Configuring Git...
      - git status
      - git add datafile/$EXPORT_FILE
      - git add .
      - git status
      - git commit -m "Uploaded export"
      - git push origin main

  post_build:
    commands:
      - echo "Starting DB import..."
      # - cp sd_imgdb/datafile/$EXPORT_FILE $EXPORT_FILE
      # - export PGPASSWORD=$DB_PASSWORD
      # - chmod +x ./script/restoredsql.sh
      #- bash ./script/restoredsql.sh
      # - psql -q -h $DB_HOST -U $DB_USER -d $DB_NAME < $EXPORT_FILE
      - echo "Imported data into existing DB instance."

artifacts:
  files:
    - $EXPORT_FILE