phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing PostgreSQL client"
      - sudo apt update -y
      - sudo apt install -y postgresql

  build:
    commands:
      # Identify previous version SQL script
      - previous_sql_file=$(ls -1t release_sql/*.sql | tail -1)
      - echo "Previous SQL file: $previous_sql_file"
      
      # Connect to the database and run the SQL script
      # - psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f "$previous_sql_file"